name: tests

on:
 workflow_call:
     inputs:
        ref:
            description: Git ref on which to run the tests.
            type: string
        options:
            description: Options to pass to pytest.
            default: --no-graphics
            type: string

jobs:
  check-format:
    uses: ./.github/workflows/check-formatting.yml

  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        if: inputs.ref != ''
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Checkout current branch
        uses: actions/checkout@v3
        if: inputs.ref == ''
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install package and test deps
        run: |
          pip install -e .[test]

      - name: Run pytest
        run: |
          pytest ${{ inputs.options }}
